### ISSUE TITLE
Use VirusTotal to Scan

### ISSUE THREAD

**Issue by c0fe** [nextcloud/files_antivirus#10]
Is it possible to have the plugin utilize VirusTotal to scan the documents by submitting them and checking the results and flagging any that are deemed suspicious or malicious? ClamAV tends false flag or not flag actually malicious ones.

**Comment by maprambo** [comment]
The api can only handle 4 requests per minute. This is even few for a family server.
https://www.virustotal.com/de/documentation/public-api/
