### ISSUE TITLE
Installed w/snap + server version wrong?

### ISSUE THREAD

**Issue by wolfsden3** [nextcloud/files_antivirus#115]
### Steps to reproduce
1.  Installed Ubuntu 18.04 LTS
2.  Installed with snap, snap install nextcloud
3.  Downloaded > extracted > moved dir for av into the "/var/snap/nextcloud/current/nextcloud/extra-apps/" folder.
4.  Logged into the web interface and looked at the apps and it says:  "This app cannot be installed because the following dependencies are not fulfilled:

    Server version 15 or higher is required."

### Expected behaviour
Is the snap not installing the latest version?  How can I install the latest version with the snap?

### Actual behaviour
I can't install AV and other apps I downloaded as version 15.

### Server configuration

**Operating system**:
Ubuntu 18.04 LTS
**Web server:**
SNAP
**Database:**
SNAP db whatever it installs
**PHP version:**
Whatever the snap installs
**Nextcloud version:** (see Nextcloud admin page)
15!  Come on!  I was hoping for 15!
**Where did you install Nextcloud from:**
SNAP

**List of activated apps:**
None, they won't activate!

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
It's all snap baby...whatever the snap is.

```
Snap snap snap snap...it's a DEFAULT SNAP INSTALLATION.

Ru Ro Raggy!  Maybe I should go install the big boy non-snap version but I thought this was quick and dirty which is what I needed but now it's turning into a project.  Ugh.

**Comment by rullzer** [comment]
Please consult about this in the snap repository.
