### ISSUE TITLE
File size limit not respected

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/files_antivirus#175]
### Steps to reproduce
1. Have files_antivirus configured with ClamAV as Daemon (Socket)
2. Configure File size limit to 20000000 bytes (20 MB)
3. Upload an infected Zip-file with 33 MB

### Expected behaviour
File scan gets bypassed, file gets uploaded

### Actual behaviour
File gets scanned and rejected

### Server configuration
- Nextcloud 20.0.0
- files_antivirus 3.0.0
- ClamAV 0.102.4

**Comment by rullzer** [comment]
Yes the filesize is for background scans. Since we don't know the filesize as it is being uploaded there we just scan the individual parts. (which are chunks of 10MB)

**Comment by wiswedel** [comment]
> the filesize is for background scans
What's the scenario for files to be scanned in background? When they've been modified at rest?

**Comment by wiswedel** [comment]
> > the filesize is for background scans
> 
> What's the scenario for files to be scanned in background? When they've been modified at rest?

@rullzer Could you please respond by the end of this week? I owe a customer an answer by Monday. Thx.

**Comment by rullzer** [comment]
> > the filesize is for background scans
> 
> What's the scenario for files to be scanned in background? When they've been modified at rest?

We just scan files in the background every 4 weeks if I'm not mistaken. So that when virus definitions get updated we also scan the files again.
