### ISSUE TITLE
Disable clamav scanning for chunks during chunked uploads

### ISSUE THREAD

**Issue by tanguy-opendsi** [nextcloud/files_antivirus#196]
Hi, it's possible to add inside config.php a var to change the size of the chunk when uploading big files.
if not.
Can you give me the code of this limit
*Edit*

It might be powerful when using clamav as daemon.
Because Nextcloud upload the chunks to clamav (heaven it's not good :p ) 
best regards

**Comment by kesselb** [comment]
Hi @tanguy-opendsi :wave: 

Good catch! This has been fixed by https://github.com/nextcloud/files_antivirus/pull/201.
