### ISSUE TITLE
files_antivirus compatibility

### ISSUE THREAD

**Issue by hellracer** [nextcloud/files_antivirus#2]
Hi,

Is this compatible to nextcloud 10.0 binary? according to the url below it should work but I think this is not really the case

https://docs.nextcloud.com/server/10/admin_manual/configuration_server/antivirus_configuration.html

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/files_antivirus/archive/stable10.zip should work with Nextcloud 10

**Comment by horstvogel** [comment]
Hello,
files antivirus works also with Nextcloud 11 Snap Installation on a Ubuntu 16.04?
On my Sytem it does not work?
Thanks

**Comment by brtptrs** [comment]
The current master branch seems to work fine with Nextcloud 11.0.1 (stable)
