### ISSUE TITLE
Change content of notification header

### ISSUE THREAD

**Issue by MichaelC2011** [nextcloud/files_antivirus#20]
Hi community,

i have a question regarding the antivirus app and the notification-header, when i try to upload an infected test-file the Nextcloud will just say "Could not upload file". I know why, but our users may be not and that could get very annoying.

Is there a possibility to change the message to "Hey, it seems you try to upload an infected file. Contact your administrator" ?

Please advise, thank you.

**Comment by eppfel** [comment]
I think a quickfix would be a proper description.

Pinging @VicDeo @MorrisJobke @icewind1991 

This does not require a change in server, right? Although I believe the notification header is redesigned right now...

**Comment by rullzer** [comment]
The header is already different in current master. Telling you it found a virus in the file you tried to upload.
