### ISSUE TITLE
Antivirus not working !

### ISSUE THREAD

**Issue by techc0de** [nextcloud/files_antivirus#200]
Hello,

I'm using Nextcloud for a few years now, but the ClamAV app isn't working anymore.
The host has ClamAV installed and running in Ubuntu 20.04 and the clamav antivirus app is enabled and configured as instructed.

Host OS: Ubuntu 20.04
Client: Nextcloud v22.0 in Docker

Antivirus mode: Daemon Socker
socket: /var/run/clamav/clamd.ctl

error message: `annot connect to "/var/run/clamav/clamd.ctl": No such file or directory (code 2)`

`
Error: stream_socket_client(): unable to connect to unix:///var/run/clamav/clamd.ctl (No such file or directory) at /config/www/nextcloud/apps/files_antivirus/lib/Scanner/ExternalClam.php#41<<closure>>OC\Log\ErrorHandler::onError()/config/www/nextcloud/apps/files_antivirus/lib/Scanner/ExternalClam.php - line 41:stream_socket_client()/config/www/nextcloud/apps/files_antivirus/lib/Scanner/ScannerBase.php - line 122:OCA\Files_Antivirus\Scanner\ExternalClam->initScanner()/config/www/nextcloud/apps/files_antivirus/lib/Controller/SettingsController.php - line 69:OCA\Files_Antivirus\Scanner\ScannerBase->scanString()/config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 217:OCA\Files_Antivirus\Controller\SettingsController->save()/config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 126:OC\AppFramework\Http\Dispatcher->executeController()/config/www/nextcloud/lib/private/AppFramework/App.php - line 156:OC\AppFramework\Http\Dispatcher->dispatch()/config/www/nextcloud/lib/private/Route/Router.php - line 301:OC\AppFramework\App::main()/config/www/nextcloud/lib/base.php - line 1000:OC\Route\Router->match()/config/www/nextcloud/index.php - line 36:OC::handleRequest()
-- `

**Comment by danieldean** [comment]
Have you checked the sockect still exists (in case you have updated, etc, since install)? On my system it was in the same location but named 'clamd.sock' not 'clamd.ctl'.

**Comment by techc0de** [comment]
Hi,

The file is exists:  `drwxr-xr-x  2 clamav root    60 Aug 14 08:05 ./
drwxr-xr-x 29 root   root   980 Aug 14 08:34 ../
srw-rw-rw-  1 clamav clamav   0 Aug 14 08:05 clamd.ctl=`

**Comment by kesselb** [comment]
Thank you for taking the time to report a problem :+1: 

As this seems to be a setup issue I would like to ask you to raise your question at https://help.nextcloud.com
