### ISSUE TITLE
Disable background scan task

### ISSUE THREAD

**Issue by js94x** [nextcloud/files_antivirus#25]
Hi, is it possible to disable the background scan task ?

**Comment by js94x** [comment]
I commented out the whole file _lib/Cron/Task.php_ and it doesn´t start anymore. 

I would appreciate it if you could offer a way to disable this feature.

**Comment by IIPoliII** [comment]
Would love to see this so we can start it only at 4am for example

**Comment by fraenki** [comment]
I'd assume that setting "File size limit for periodic background scans" to "0 bytes" would probably be an acceptible workaround. (Of course, the cron job would still scan all files, which takes some time, but it would at least not check everything with ClamAV.)

**Comment by michag86** [comment]
This feature was added with this commit:
https://github.com/nextcloud/files_antivirus/commit/5f76956433695537e47ca21e1625228b330dc1db

You can disable background scan with occ:
occ config:app:set files_antivirus av_background_scan --value="off"

I think this can be closed.

**Comment by digitalrevisor** [comment]
hmm.. in the documentation the command is missing a " - "
occ config:app:set files_antivirus av_background_scan –value=”off” Does not work.
But as described in the above comment:
occ config:app:set files_antivirus av_background_scan --value="off" Works.
