### ISSUE TITLE
no clamav for nextcloud 12?

### ISSUE THREAD

**Issue by JK74** [nextcloud/files_antivirus#26]
not sure if this the right way but I'm missing the clamav in NC12 or is not planned or not available (yet)?

**Comment by GieltjE** [comment]
Guess this is linked to #19 as it was a pain to install in v11 too.

**Comment by BornToBeRoot** [comment]
Adding it to the app store would make it a lot easier to install.

**Comment by boina** [comment]
Do we know if there will be a version for nextcloud 12??

**Comment by JK74** [comment]
Yes its now available: https://www.c-rieger.de/nextcloud-more-secure-using-clamav/
