### ISSUE TITLE
Error Background-scan -> Cron.php 

### ISSUE THREAD

**Issue by gspu** [nextcloud/files_antivirus#27]
Upload Check works fine
Background Check with ClamAV should start, but this error appears:

{"reqId":"2sdXUih7nJ4Q+tlnVvdF","remoteAddr":"","app":"files_antivirus","message":"OCA\\Files_Antivirus\\BackgroundScanner::run, exception: An exception occurred while executing 'SELECT fc.\"fileid\", mnt.\"user_id\" FROM \"oc_filecache\" fc LEFT JOIN \"oc_files_antivirus\" fa ON fa.\"fileid\" = fc.\"fileid\" INNER JOIN \"oc_mounts\" mnt ON (fc.\"storage\" = mnt.\"storage_id\") AND (mnt.\"mount_point\" = '\/' || mnt.\"user_id\" || '\/')) WHERE (fc.\"mimetype\" <> '2') AND ((fa.\"fileid\" IS NULL) OR (fc.\"mtime\" > fa.\"check_time\")) AND (fc.\"path\" LIKE 'files\/%') AND (fc.\"size\" <> '0')':\n\nSQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near \")\"\nLINE 1: ... (mnt.\"mount_point\" = '\/' || mnt.\"user_id\" || '\/')) WHERE (f...\n                                                             ^","level":3,"time":"2017-05-18T10:45:02+00:00","method":"--","url":"--","user":"--","version":"11.0.3.2"}

FreeBSD 11 amd64
Nginx 1.12.0
Postgresql 9.6.3
PHP 5.6.3
Nexcloud 11.0.3 php-fpm (Antivirus-App 1.0.0 MASTER from Github Date 2017-05-18)
ClamAV 0.99.2/23394   (socket)

**Comment by c0r3dump3d** [comment]
I have the same error in a Nextcloud 12 installation:

`OCA\Files_Antivirus\BackgroundScanner::run, exception: An exception occurred while executing 'SELECT "fc"."fileid", "mnt"."user_id" FROM "oc_filecache" "fc" LEFT JOIN "oc_files_antivirus" "fa" ON "fa"."fileid" = "fc"."fileid" INNER JOIN "oc_mounts" "mnt" ON ("fc"."storage" = "mnt"."storage_id") AND ("mnt"."mount_point" = '/' || "mnt"."user_id" || '/')) WHERE ("fc"."mimetype" <> '2') AND (("fa"."fileid" IS NULL) OR ("fc"."mtime" > "fa"."check_time")) AND ("fc"."path" LIKE 'files/%') AND ("fc"."size" <> '0')': SQLSTATE[42601]: Syntax error: 7 ERROR: error de sintaxis en o cerca de «)» LINE 1: ...nt"."mount_point" = '/' || "mnt"."user_id" || '/')) WHERE ("... ^
`

CentOS 7.4
Apache/2.4.6 (CentOS)
Nextcloud 12.0.3.3
PHP 5.6.31
PostgreSQL 9.6.2
ClamAV Version: 0.99.2

**Comment by rullzer** [comment]
Should be fixed since I changed the query a bit
