### ISSUE TITLE
wish: add more antivirus providers

### ISSUE THREAD

**Issue by HirIMogul** [nextcloud/files_antivirus#3]
First, files_antivirus is a wonderfull and highly necessary idea!

Unfortunately ClamAV has a very poor detection rate in both windows and linux malware. 

https://www.av-test.org/en/news/news-single-view/linux-16-security-packages-against-windows-and-linux-malware-put-to-the-test/

Therefore i kindly ask, if you could add more AV providers. Especially Sophos, as it is one of the free (but not opensource) alternatives, which shows considerable high detection rates and has a low system food print.

Would it be difficult to implement this?

Best wishes!
HirIMogul

**Comment by BornToBeRoot** [comment]
Masye also add support for Kaspersky?!

**Comment by markuman** [comment]
Possible with 3.0.0

Can be closed.
