### ISSUE TITLE
Improve message if infected files was detected/deleted

### ISSUE THREAD

**Issue by BornToBeRoot** [nextcloud/files_antivirus#30]
When uploading an infected file... the message "Unsupported Media Type" is shown. For the user is not clear what happened with his file.

### Steps to reproduce
1. Upload an infected file
2. See the message (stream)

### Expected behaviour
Message like: "Infected file was detected and automatically deleted"

### Actual behaviour
![image](https://cloud.githubusercontent.com/assets/16019165/26406121/a2dab69c-4097-11e7-9d7f-70490796890e.png)

### Server configuration
**Operating system**: CentOS 7

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.0

**Nextcloud version:** 12.0.0

**Where did you install Nextcloud from:** .tar.gz-file`

**Where did you install files_antivirus from:** Latest version from Github (stable12)

#### Nextcloud log (data/owncloud.log)
![image](https://cloud.githubusercontent.com/assets/16019165/26406181/d53c7954-4097-11e7-8b03-4ea23cd48534.png)

**Comment by arianit** [comment]
Yes, please.

**Comment by rullzer** [comment]
This is fixed in current master. It now show a proper warning (at least on stable13 and master)
