### ISSUE TITLE
Info XML not for Nextcloud 12?

### ISSUE THREAD

**Issue by horstvogel** [nextcloud/files_antivirus#31]
The Info XML. Only for Nextcloud 13??
![infoxml](https://cloud.githubusercontent.com/assets/25108737/26559110/cbd86d40-44ad-11e7-8348-677711cbc89d.png)

**Comment by BornToBeRoot** [comment]
See https://github.com/nextcloud/files_antivirus/tree/stable12

**Comment by SomeStrangeName** [comment]
Looks like this app is no longer mantained right? If Nextcloud is serious in security (as they mention https://scan.nextcloud.com/) why is this app not in the app store (https://apps.nextcloud.com/)? Especially for file sharing a working anti virus seem a good idea.

**Comment by rullzer** [comment]
If I'm not mistaken in the current state it is 12-14 compatible.

I'm trying to cleanup this app a bit. Once that is done (and some testing) I'll also make sure it is added to the appstore.
