### ISSUE TITLE
desktop-client upload virus not detected

### ISSUE THREAD

**Issue by mzeyrek** [nextcloud/files_antivirus#33]
### Steps to reproduce
1.Downloaded eicar.com eicar.com.txt test viruses, 
2. Copied to nextcloud home folder and synced immediately with server over nextcloud-client 
3. Viruses doesn't get deleted, able to copy files
4. Tried same upload from chrome/firefox web browser, upload fails system warns about virus detection and deletes file which is normal behaviour.

**Operating system**:
Debian 9 Stretch
**Web server:**
nginx/1.10.3
**Database:**
MariaDB 10.2
**PHP version:**
7.0
**Nextcloud version:** (see Nextcloud admin page)
12

**Comment by rullzer** [comment]
I just tested this against master and stable13 and it works as expected for me now.
