### ISSUE TITLE
Can't find Antivirus App in Nextcloud 12

### ISSUE THREAD

**Issue by hostingnuggets** [nextcloud/files_antivirus#37]
I can't find this Antivirus App in the Apps web admin panel in Nextcloud version 12. Does anyone know what happened to this app? or is it not compatible with Nextcloud 12?

**Comment by BornToBeRoot** [comment]
Duplicate #26 
You have to download it from github and extract it into your `apps/` folder, change permissions, then enable it in the admin interface...

**Comment by hostingnuggets** [comment]
Thanks, would be nice to have it in the Nextcloud app store.
