### ISSUE TITLE
`ILogger` is deprecated and will be removed

### ISSUE THREAD

**Issue by susnux** [nextcloud/files_antivirus#376]
The `ILogger` interface is deprecated and its logging functions will be removed with Nextcloud 31.
Please migrate to the PSR LoggerInterface. The logging levels inside `ILogger` will remain, but we recommend to use the logging levels provided by PSR-3.

Code reference:

https://github.com/nextcloud/files_antivirus/blob/e2d4c648cbb2214d19c27b4adc7421c5560e16df/tests/stub.phpstub#L74

cc @come-nc @icewind1991

**Comment by icewind1991** [comment]
Just a stub
