### ISSUE TITLE
Log infected files on upload

### ISSUE THREAD

**Issue by michag86** [nextcloud/files_antivirus#4]
If a user trys to upload an infected file, this is not logged.
With a newer version notification to the user is added. But as admin, it's not easy to check which user and which file is affected.

I've tested this on ownCloud 8.2 with files_antivirus 0.8.0.1. This is not the latest version, but newer are also affected.

Maybe it's possible to add a log entry here:
https://github.com/nextcloud/files_antivirus/blob/2b900fc046168f0b3a9839da9d0114904787a1d2/lib/avirwrapper.php#L98

Something like that:
`$this->logger->warning('Virus ' . $status->getDetails() . ' is detected in the file: ' . $path . '. Upload by ' . $owner  . ' cannot be completed.');
`

**Comment by MorrisJobke** [comment]
Fixed with #6
