### ISSUE TITLE
Found by backgroundscanner is only moved to trashbin

### ISSUE THREAD

**Issue by michag86** [nextcloud/files_antivirus#5]
If an infected file is found and action is set to delete, the file is moved to trashbin.
https://github.com/nextcloud/files_antivirus/blob/0a4ea3c924a19b83c40f1c31b80cdc729dddfcc1/lib/item.php#L143-L150

I think that should be implemented like this:
https://github.com/nextcloud/files_antivirus/blob/2b900fc046168f0b3a9839da9d0114904787a1d2/lib/avirwrapper.php#L80

BTW: The Item class is already prepared to be usable by scan on demand. I don't know if the AvirWrapper can use the item class?

**Comment by MorrisJobke** [comment]
Fixed with #7
