### ISSUE TITLE
Proper activity icon

### ISSUE THREAD

**Issue by rullzer** [nextcloud/files_antivirus#67]
@nextcloud/designers 

Currently we have the app icons at: https://github.com/nextcloud/files_antivirus/tree/master/img

However this doesn't show up properly in the activity list:

![av_ac](https://user-images.githubusercontent.com/45821/37023407-1f20a81e-2126-11e8-8066-33a71e2e305e.png)

I guess we need the icon in dark.

**Comment by skjnldsv** [comment]
I'll go for a shield or something like that :)
Or a real virus icon (but it may look childish, we need to see) ;)

**Comment by rullzer** [comment]
There already is a shield in https://github.com/nextcloud/files_antivirus/tree/master/img ;) But I need it dark (same dark as all the other icons etc).

**Comment by skjnldsv** [comment]
I'll guess this was a good idea then :stuck_out_tongue_winking_eye:

**Comment by pixelipo** [comment]
@rullzer https://github.com/nextcloud/server/pull/7319 gives ability to have a single svg icon for both white (`.icon-white` class ) and black versions. If you want to use that, I can update the icon in a PR.

**Comment by MorrisJobke** [comment]
> @rullzer nextcloud/server#7319 gives ability to have a single svg icon for both white (.icon-white class ) and black versions. If you want to use that, I can update the icon in a PR.

Makes sense 👍

**Comment by rullzer** [comment]
@pixelipo please!

**Comment by juliushaertl** [comment]
The invert filter from #7319 will not work with IE11 iirc, that is why we reintroduced the svg inline filter for the app menu again.

**Comment by rullzer** [comment]
See #73
