### ISSUE TITLE
Activity icon (virus found)

### ISSUE THREAD

**Issue by rullzer** [nextcloud/files_antivirus#68]
It would be nice to have some kind of virus icon to show next to the activity text.

![av_ac_list](https://user-images.githubusercontent.com/45821/37023447-4a501ab0-2126-11e8-983a-5a10f3fef5c9.png)

CC: @nextcloud/designers

**Comment by skjnldsv** [comment]
A search icon? An exclamation point?

**Comment by rullzer** [comment]
Don't know. Don't care. Just something I guess. Bug/Virus icon? But I'm also fine with anything for now. We can always change it later.

**Comment by MariusBluem** [comment]
monitoring icon :) (Heart frequency -> Health -> Virus)

**Comment by rullzer** [comment]
Somebody create a PR with the icon and I'll do the rest ;)

**Comment by MorrisJobke** [comment]
> Bug/Virus icon?

I somehow like this xD But maybe a shield also looks nice and better as a way to say "protected" :)

![37023447-4a501ab0-2126-11e8-983a-5a10f3fef5c9](https://user-images.githubusercontent.com/245432/37027334-57b26fd6-2131-11e8-8ee2-3fb6b8a78e5f.png)

**Comment by rullzer** [comment]
@MorrisJobke I guess I need  both. Because (right now) for background scan there is the option to not delete the file and just to notify the user.

**Comment by jancborchardt** [comment]
Agree with Morris, a shield is better here (should also be the app icon).

@rullzer can we be more specific than "It is going to be deleted"? Like "It will be deleted in 24 hours as precaution. You can restore it from the deleted files."

**Comment by jancborchardt** [comment]
Ah well, the app icon is a shield already ;)
https://github.com/nextcloud/files_antivirus/blob/master/img/app.svg

**Comment by rullzer** [comment]
@jancborchardt yeah need to fix that actually. Also the text is wrong. As it is already deleted. This is the warning when a file is uploaded that contains a virus (that we just don't allow, so the text is a lie).

If the admin sets the background scan he can chose to only log or also delete. The default is log. But if he choses delete the file is deleted directly (and not stored in the trash).

My problem with a shield in both cases is that it makes it seem like you are protected. While if the file is not deleted you are not protected. I'm fine with a shield if it is just a notification. But if there still is a known infected file on your instance something that doesn't look so safe should be used I guess

**Comment by rullzer** [comment]
Anyway let me create a PR with some icons and new text to show what I mean. I guess that makes the discussion easier.

**Comment by rullzer** [comment]
See #69 for a first draft

**Comment by rullzer** [comment]
![ac2](https://user-images.githubusercontent.com/45821/37042831-85511c98-215f-11e8-95fd-0d789fec023c.png)

Latest state. For fancier icons or wording please open a PR or issue ;)

**Comment by MorrisJobke** [comment]
@rullzer Is it possible to remove the transferID and part stuff ... internals that don't matter for end users and only confuse people.

**Comment by MorrisJobke** [comment]
#72
