### ISSUE TITLE
Improve file name for blocked uploads

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/files_antivirus#72]
Current way:

![ac2](https://user-images.githubusercontent.com/45821/37042831-85511c98-215f-11e8-95fd-0d789fec023c.png)

Is it possible to remove the transferID and part stuff ... internals that don't matter for end users and only confuse people.

cc @rullzer

**Comment by rullzer** [comment]
@MorrisJobke it is already for new ones. The ones with a badge are all that is generated now. I can't fix the old stuff ;) Well I could. But I don't care enough.

**Comment by MorrisJobke** [comment]
> @MorrisJobke it is already for new ones. The ones with a badge are all that is generated now. I can't fix the old stuff ;) Well I could. But I don't care enough.

Okay so new activities don't have this in them anymore? Then you can close this ticket.

**Comment by rullzer** [comment]
No new activities do not :)
