### ISSUE TITLE
Error when inserting clean files with Postgresql

### ISSUE THREAD

**Issue by claudex** [nextcloud/files_antivirus#86]
### Steps to reproduce
1. Have Postgresql as DB backend
2. Upload a file 
3. Wait for the background scan to happen and view the logs

### Expected behaviour
There should not be any error in the logs

### Actual behaviour
The following error is visible:

>OCA\Files_Antivirus\Item::processClean, exception: An exception occurred while executing 'SELECT lastval()': SQLSTATE[55000]: Object not in prerequisite state: 7 ERROR: lastval is not yet defined in this session

### Server configuration

**Operating system**: Debian

**Web server:** Apache

**Database:** Postgresql

**PHP version:** 7.0.27

**Nextcloud version:** 13.0.2

**Where did you install Nextcloud from:** tar.gz

#### Nextcloud log (data/owncloud.log)

```
{"reqId":"baktXEb7uh9caHQigiuf","level":3,"time":"2018-06-07T09:39:02+00:00","remoteAddr":"","user":"--","app":"files_antivirus","method":"--","url":"--","message":"OCA\\Files_Antivirus\\Item::processClean, exception: An exception occurred while executing 'SELECT lastval()':\n\nSQLSTATE[55000]: Object not in prerequisite state: 7 ERROR:  lastval is not yet defined in this session","userAgent":"--","version":"13.0.2.1"}
```

From my understanding, the error happens because the Postgresql function "lastval" [is called](https://github.com/nextcloud/server/blob/master/lib/private/DB/AdapterPgSql.php#L29) in the [insert method](https://github.com/nextcloud/server/blob/master/lib/public/AppFramework/Db/Mapper.php#L132) of the Mapper class. Itself called [in the processClean method](https://github.com/nextcloud/files_antivirus/blob/master/lib/Item.php#L144) in the Item call.

Since, there is no sequence in the table `files_antivirus` (only `fileid` and `checktime`), Postgresql function `nextval`  is not called and so, calling `lastval` throws the error.

I don't know if the table `files_antivirus` should have a primary key with a sequence or if the class `Mapper` should be fixed instead.

**Comment by pcurie** [comment]
Hello,

I have the same problem, nextcloud 13.0.4, php 7.0.27 on CentOS 7.4, postgresql database, installation from .tar.gz

Thanks

**Comment by Cliffhou** [comment]
same issue here

**Comment by jgmage** [comment]
Same here.  Ubuntu 18.04, php-fpm 7.2.7, postgresql 10.5, nextcloud 13.0.5.2, version 1.3.1 of this app, nginx 1.14.0, installation from zip.

{"reqId":"I7SuW7YYrvW3mlBAjF7T","level":3,"time":"August 19, 2018 19:47:00","remoteAddr":"","user":"--","app":"files_antivirus","method":"--","url":"--","message":"OCA\\Files_Antivirus\\Item::processClean, exception: An exception occurred while executing 'SELECT lastval()':\n\nSQLSTATE[55000]: Object not in prerequisite state: 7 ERROR:  lastval is not yet defined in this session","userAgent":"--","version":"13.0.5.2"}

**Comment by charliewutwut** [comment]
I see the same on FreeBSD 11.2-STABLE, Nginx 1.14.0_12, PHP-FPM 7.1.22, PostgreSQL 10.5 backend, Nextcloud 14.0.1.1, 'Antivirus for files' 1.3.2. 
The app is install from the 'Store', rest is from FreeBSD repo, builded on own Poudriere installation.
It also occurred before upgrading to NC14 from NC13.0.5.

{"reqId":"RbFQBGvKXQlmOQyX9trj","level":3,"time":"27-Sep-2018 21:30:02","remoteAddr":"","user":"--","app":"files_antivirus","method":"","url":"--","message":"OCA\\Files_Antivirus\\Item::processClean, exception: An exception occurred while executing 'SELECT lastval()':\n\nSQLSTATE[55000]: Object not in prerequisite state: 7 ERROR:  lastval is not yet defined in this session","userAgent":"--","version":"14.0.1.1"}
